language: python
python:
- '2.7'
install:
- pip install slackclient
- pip install urllib3
script: ./unittests
notifications:
  slack:
    secure: VnGm8+FlYK4sqIVR1O/Y2WlZiE0QZnoRnzs1yWfHGvzL4Yqxs05X2/fmvDZNJ+EB4e2rdqKCA+MOUCdppg6l7xQbBSMJgbjL7Uatw7RnNczziarHIP4gvOmwQzzJkJTEMXsh5es7X0Bjp0Q4KhUqhU4MftUWLJMEaZWdW5q5houwaNODkC1pg7cWAuCwjjVBJXj5LJG9LNHvtF9G9iQtdgdRckorQafk+v+SUR5N7NwBgrG6bAqLZgPXtG7UiKGFBdJ5udbahKYrogV8Ne+n0QVllbU/5MQBp8xcbfENJ6fTEHUEksuzMiAjCX1IQMrUXe0QFflhiSDIjEGDiP2O3klYOaXMruS4+CpfGK67Z+5j6RQzn1Rdrg3F2veVBz7YQTBwZzvcv/y5Ep/mlRsk8DKDXuVN2Lh+WxGGq1gZAlKYdcNd+cNYx+E2f/RnRwYsNy5LT9B9O86upBNwWr5k8S5I6H5S3Ui8KwcelTrDuSb7hdxa+clrIouR2usPU7wdl7/1eP0LnAjSbaA+Dn2SaOLWh6HSA7/GrkJPqdvMlVoDx9RxNW60HErGqEBBqEPlPXzf3QZZWTSV+TR96/4holb9mXJBLjuYabXUmq3Lz+6hBLFH/I5kV3PaLqjmE5D+4oDp0gcQF1oKfzbTRTDFeAPWNTXiPfqJbdlGYOnwrlQ=
deploy:
  provider: pypi
  skip_cleanup: true
  user: wray
  password:
    secure: ooWrw9Xa0QRwsikjEphe9wOIZqYYC5Uai7m/W8HOF+8YLrvTbJOhds38ZKOmyzjcGwW3KoIgPdSx3zWsmBWXUPEOOOsppQzLPdpiQMUPPFxt1dlWU0VoUpgM3u1fY8IO3LTYbbyfy14/8YMe3hluq0b1Uki/TlM/Bd1d+ddL4IG8Epi/puUW7ZGJ/P51Hci1v0xLKxdr9W4zTZwkOsXQRaDfTEO0UXGWVpXlfjP2b1H8N25nqGXa/ouLhsKg+O+76Qz18dLZel3r1AaxZyQtRsViPU4E4SFYjwdWRsU//0UXqlzgP9PSsaogboSbvRtZi2P6OkBeR9sxap3Ojt0vTirsz/kTmj9wbvIt5BdQRHMtvsp1bNIGyOHOeRY+khaEMN+nZarx+Pb2R3FESaFftGO6Nim7OKEc+tWw4aeHGBv1+eMk2Cgfge9AGzAuHW2ZKucaeyo8kSIxmLlhrgI7cnE3ty4xxFxL9/zY5GhOd1b2QM2oGe1/YJykANmLn+wuxwstuFsolJI78KSgCWD7VqEQD8P6JCSGq4L25/np+wGvCmUS8s/k2H1jTSmakL7FXdkMqDzn6+hAOEISEIzP67cnbcC2z9d+cZR+ejz71uhGbbi1Gq+hekd5JZaq+Z9/Nho8euC9joZx/K5PrIp7nDk4hJKgtVxZbNUt5+K6e8k=
