language: python
python:
- '2.7'
install:
- pip install slackclient
- pip install urllib3
script: ./unittests
notifications:
  slack:
    secure: VnGm8+FlYK4sqIVR1O/Y2WlZiE0QZnoRnzs1yWfHGvzL4Yqxs05X2/fmvDZNJ+EB4e2rdqKCA+MOUCdppg6l7xQbBSMJgbjL7Uatw7RnNczziarHIP4gvOmwQzzJkJTEMXsh5es7X0Bjp0Q4KhUqhU4MftUWLJMEaZWdW5q5houwaNODkC1pg7cWAuCwjjVBJXj5LJG9LNHvtF9G9iQtdgdRckorQafk+v+SUR5N7NwBgrG6bAqLZgPXtG7UiKGFBdJ5udbahKYrogV8Ne+n0QVllbU/5MQBp8xcbfENJ6fTEHUEksuzMiAjCX1IQMrUXe0QFflhiSDIjEGDiP2O3klYOaXMruS4+CpfGK67Z+5j6RQzn1Rdrg3F2veVBz7YQTBwZzvcv/y5Ep/mlRsk8DKDXuVN2Lh+WxGGq1gZAlKYdcNd+cNYx+E2f/RnRwYsNy5LT9B9O86upBNwWr5k8S5I6H5S3Ui8KwcelTrDuSb7hdxa+clrIouR2usPU7wdl7/1eP0LnAjSbaA+Dn2SaOLWh6HSA7/GrkJPqdvMlVoDx9RxNW60HErGqEBBqEPlPXzf3QZZWTSV+TR96/4holb9mXJBLjuYabXUmq3Lz+6hBLFH/I5kV3PaLqjmE5D+4oDp0gcQF1oKfzbTRTDFeAPWNTXiPfqJbdlGYOnwrlQ=
deploy:
  provider: pypi
  skip_cleanup: true
  user: wray
  password:
    secure: bhmJXCKqMTv76nCd5JLJ1k3biGS4dCYUrjDgTwSA0g3p1jkBYkVMJs36P4Bvolq+M/4m+mMfGYie0Bk0NGz3BJoedDsF+bvtq/vEYwFQLnZnsCf6RkwpVtdpwcll8JLOUBPbHCuqIsjekwQqf8zrE/U1p56x8NGlG9kRPBDxM3fwIgmc7nEV8vlAFJTChRif4nBPnbGHhJMlKLx5j4NsvTZehEI1674P2tTNhSXd4BX8BBOsiPfxSvyWqDCcb/VJqLLo7dfrE0Ar/w6GrQHlCY/25gy41Rmrv4o2v2ZTHQ2nCFXmvHCT4qsFZULE/IujrU0qNuGVqXQqT4AI/IlkoGD1H6nb8NLjkousJpkmgRyiEIbJ3bMeHoVzNSKckw5Cm8ioFD2HqVkU+tFTk2IyUsUX1x3iSdQLPAf87IHaHKwfh1iiwTezsPZbqET53AWTg3DuUL9wE/C//w+96RzkKd1fZZbLln9q9EIrSEvaKP7m4gGPBQazrg4gbX3oBZ/5el3OFYfwb0rDhPAQLgLWsoz3Bi1coMFw3bcWJqSYP8iLHG/hsQTFjDhy7+eZof8SZgCaxSXW/q2Bpd4nHYsZor9brjqpa4f8CKiOQcS6t8XmghzDty0ZdiNaaNlQ1TrkA3Wn6IwPNuonXdQPxAnpVj23wuKhH2y+nqCxl6QyED4=
